spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch
    username: 'root'
    password:
  sql:
    init:
      platform: mysql